### ISSUE TITLE
Missing files in OpenSteer project for windows

### ISSUE THREAD

**Issue by Ezeer** [meshula/OpenSteer#1]
Hi .
When we want to build the opensteer demo , the linker fails because of missing source files .
I manually fixed that , the demo works now , but the visual solution in the repository should be fixed .
Missing files in the project that build the lib are : 

Path.cpp
Pathway.cpp
PolylineSegmentedPath.cpp
PolylineSegmentedPathwaySegmentRadii.cpp
PolylineSegmentedPathwaySingleRadius.cpp

thx

**Comment by meshula** [comment]
Fixed by switch to Cmake build system.
